release: "github"
github:
  repo: "ngx-validators"
  user: "nightapes"
commitFormat: angular
branch:
  master: release
hooks:
  preRelease:
    - yarn version --new-version $(./go-semantic-release next)
    - yarn build
    - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> ~/.npmrc
    - yarn publish dist/ngx-validators
